name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  verify-swift-package:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Create .netrc file with credentials to download binaries from SAP RSBC
      uses: little-core-labs/netrc-creds@master
      with:
        machine: rbsc.repositories.sap.ondemand.com
        login: sap-sdkiospecs
        password: ${{ secrets.RSBC_USER_BASICAUTH_PWD }}
    - name: Check download of binary frameworks
      run: swift package resolve
